import streamlit as st
import io
import matplotlib.pyplot as plt
import numpy as np
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from PIL import Image

def create_risk_map_image(lat, lon, risk_score, features=None):
    """Create a risk map image using matplotlib (works on Streamlit Cloud)"""
    
    try:
        # Create figure
        fig = plt.figure(figsize=(12, 10), dpi=150)
        ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
        
        # Add map features
        ax.add_feature(cfeature.LAND, color='#f0f0f0', edgecolor='#cccccc', linewidth=0.5)
        ax.add_feature(cfeature.OCEAN, color='#e6f3ff')
        ax.add_feature(cfeature.COASTLINE, linewidth=0.8, edgecolor='#333333')
        ax.add_feature(cfeature.BORDERS, linewidth=0.5, edgecolor='#666666', linestyle=':')
        ax.add_feature(cfeature.LAKES, color='#e6f3ff', edgecolor='#cccccc')
        ax.add_feature(cfeature.RIVERS, color='#99ccff', linewidth=0.5)
        
        # Set extent (10km radius around location)
        lat_offset = 0.09  # ~10km
        lon_offset = 0.09 / np.cos(np.radians(lat))
        ax.set_extent([lon - lon_offset, lon + lon_offset, lat - lat_offset, lat + lat_offset])
        
        # Add risk color circle
        if risk_score < 40:
            color = '#4CAF50'  # Green
            risk_text = "LOW RISK"
        elif risk_score < 70:
            color = '#FFC107'  # Yellow
            risk_text = "MEDIUM RISK"
        else:
            color = '#F44336'  # Red
            risk_text = "HIGH RISK"
        
        # Plot main location marker
        ax.plot(lon, lat, 'o', markersize=15, color=color, 
                transform=ccrs.PlateCarree(), zorder=10, markeredgecolor='white', 
                markeredgewidth=2)
        
        # Add risk circle
        theta = np.linspace(0, 2*np.pi, 100)
        radius = 0.03  # ~3km radius
        x_circle = lon + radius * np.cos(theta)
        y_circle = lat + radius * np.sin(theta)
        ax.fill(x_circle, y_circle, color=color, alpha=0.3, transform=ccrs.PlateCarree(), zorder=5)
        
        # Add text annotation
        ax.annotate(f'{risk_score:.1f}%', xy=(lon, lat), xytext=(5, 5),
                   textcoords='offset points', fontsize=14, fontweight='bold',
                   color='white', backgroundcolor=color, 
                   bbox=dict(boxstyle='round,pad=0.3', facecolor=color, alpha=0.9),
                   transform=ccrs.PlateCarree())
        
        # Add title
        ax.set_title(f'GeoGuard Risk Analysis Report', fontsize=16, fontweight='bold', pad=20)
        
        # Add location text
        ax.text(0.5, -0.1, f'Location: {lat:.6f}°N, {lon:.6f}°E | Risk Score: {risk_score:.1f}%',
                transform=ax.transAxes, fontsize=10, ha='center', va='top',
                bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
        
        # Add risk level banner at top
        banner_color = '#4CAF50' if risk_score < 40 else ('#FFC107' if risk_score < 70 else '#F44336')
        fig.patch.set_facecolor(banner_color)
        
        # Add legend for factors if provided
        if features:
            factor_text = " | ".join([f"{k}: {v:.0f}%" for k, v in list(features.items())[:3]])
            ax.text(0.5, -0.18, factor_text, transform=ax.transAxes, fontsize=8, 
                   ha='center', va='top', style='italic')
        
        # Add footer
        ax.text(0.5, -0.22, 'Generated by GeoGuard AI - Border Terrain Risk Analyzer',
                transform=ax.transAxes, fontsize=8, ha='center', va='top', color='#888888')
        
        plt.tight_layout()
        
        # Convert to PIL Image
        img_bytes = io.BytesIO()
        plt.savefig(img_bytes, format='PNG', dpi=150, bbox_inches='tight', facecolor='white')
        plt.close()
        
        img_bytes.seek(0)
        return Image.open(img_bytes)
        
    except Exception as e:
        st.error(f"Error generating map: {e}")
        return None

def create_simple_map_preview(lat, lon):
    """Create a simple quick preview map"""
    try:
        fig, ax = plt.subplots(figsize=(8, 6))
        
        # Simple plot
        ax.plot(lon, lat, 'ro', markersize=12, markeredgecolor='white', markeredgewidth=2)
        
        # Add grid and labels
        ax.grid(True, alpha=0.3)
        ax.set_xlabel('Longitude')
        ax.set_ylabel('Latitude')
        ax.set_title(f'Location: {lat:.4f}, {lon:.4f}')
        
        # Set margins
        margin = 0.1
        ax.set_xlim(lon - margin, lon + margin)
        ax.set_ylim(lat - margin, lat + margin)
        
        plt.tight_layout()
        
        img_bytes = io.BytesIO()
        plt.savefig(img_bytes, format='PNG', dpi=100)
        plt.close()
        
        img_bytes.seek(0)
        return Image.open(img_bytes)
        
    except Exception as e:
        return None