from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from datetime import datetime
import os

def generate_risk_report(lat, lon, risk_score, risk_level, factors, filename="GeoGuard_Report.pdf"):
    """Generate a PDF report for risk analysis"""
    
    doc = SimpleDocTemplate(filename, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#667eea'),
        alignment=1  # Center alignment
    )
    story.append(Paragraph("🛡️ GeoGuard Risk Assessment Report", title_style))
    story.append(Spacer(1, 0.25*inch))
    
    # Report Info
    info_style = styles['Normal']
    story.append(Paragraph(f"<b>Date & Time:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", info_style))
    story.append(Paragraph(f"<b>Location:</b> {lat:.6f}°N, {lon:.6f}°E", info_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Risk Score Section
    story.append(Paragraph("<b>Risk Assessment Results</b>", styles['Heading2']))
    story.append(Spacer(1, 0.1*inch))
    
    # Risk Score Table
    risk_data = [
        ["Metric", "Value"],
        ["Risk Score", f"{risk_score:.1f}%"],
        ["Risk Level", risk_level]
    ]
    
    risk_table = Table(risk_data, colWidths=[2*inch, 2*inch])
    risk_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#667eea')),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 14),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(risk_table)
    story.append(Spacer(1, 0.2*inch))
    
    # Risk Factors
    story.append(Paragraph("<b>Key Risk Factors</b>", styles['Heading2']))
    story.append(Spacer(1, 0.1*inch))
    
    factors_data = [["Factor", "Value"]]
    for name, value in factors.items():
        factors_data.append([name, f"{value:.0f}%"])
    
    factors_table = Table(factors_data, colWidths=[3*inch, 1.5*inch])
    factors_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#764ba2')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(factors_table)
    story.append(Spacer(1, 0.2*inch))
    
    # Recommendations
    story.append(Paragraph("<b>Recommendations</b>", styles['Heading2']))
    story.append(Spacer(1, 0.1*inch))
    
    if risk_score < 40:
        rec_text = "• Low risk area - Continue normal monitoring\n• Maintain regular surveillance\n• No immediate action required"
    elif risk_score < 70:
        rec_text = "• Medium risk area - Increase patrol frequency\n• Monitor weather conditions\n• Conduct regular assessments"
    else:
        rec_text = "• HIGH RISK AREA - Immediate attention required\n• Deploy additional resources\n• Evacuation plan recommended\n• Continuous monitoring needed"
    
    story.append(Paragraph(rec_text.replace('\n', '<br/>'), styles['Normal']))
    story.append(Spacer(1, 0.2*inch))
    
    # Footer
    story.append(Spacer(1, 0.5*inch))
    footer_text = f"<i>Generated by GeoGuard AI - Border Terrain Risk Analyzer | {datetime.now().year}</i>"
    story.append(Paragraph(footer_text, styles['Italic']))
    
    # Build PDF
    doc.build(story)
    return filename